### ISSUE TITLE
missing parameters not handled

### ISSUE THREAD

**Issue by nkh** [awsome-utils/diff-folders#10]
diff-folders #no parameters given
 
thread 'main' panicked at 'diff-folders <old_dir|new_file> <new_dir|new_file>', /home/nadim/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diff-folders-0.0.1/src/main.rs:22:9

**Comment by wanglong001** [comment]
This is as expected, if the number of parameters is wrong, it will directly panic
